# Generated by Django 3.1.4 on 2021-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueESMT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prerequis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
