# Generated by Django 3.1.4 on 2021-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueESMT', '0002_auto_20210127_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
