# Generated by Django 3.1.4 on 2021-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueESMT', '0003_auto_20210202_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='prerequis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
